# Generated by Django 4.2.21 on 2025-05-16 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
    ]
