# Generated by Django 4.2.21 on 2025-05-20 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('country', models.CharField(choices=[('IN', 'India'), ('US', 'United States'), ('UK', 'United Kingdom')], default='IN', max_length=2)),
            ],
        ),
    ]
