# Generated by Django 4.2.21 on 2025-05-23 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='mcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('sku', models.CharField(max_length=25)),
                ('price', models.FloatField()),
                ('qty', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='mproduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('sku', models.CharField(max_length=25)),
                ('price', models.FloatField()),
                ('qty', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='my_app.mcategory')),
            ],
        ),
    ]
