# Generated by Django 4.2.21 on 2025-05-23 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_mcategory_mproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mproduct',
            name='category',
        ),
        migrations.AddField(
            model_name='mproduct',
            name='category_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_app.mcategory'),
        ),
    ]
