# Generated by Django 4.2.21 on 2025-05-23 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_remove_mcategory_price_remove_mcategory_qty_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mproduct',
            name='updated_at',
        ),
    ]
