# Generated by Django 4.2.21 on 2025-05-23 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_remove_mproduct_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mproduct',
            name='created_at',
        ),
    ]
