# Generated by Django 4.2.21 on 2025-05-23 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_remove_mproduct_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mproduct',
            old_name='category_id',
            new_name='category',
        ),
    ]
