# Generated by Django 4.2.21 on 2025-05-23 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0008_rename_category_id_mproduct_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='mcustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=40, unique=True)),
                ('password', models.CharField(max_length=400)),
            ],
        ),
    ]
