# Generated by Django 4.2.21 on 2025-06-04 09:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0011_alter_address_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default=uuid.uuid4, max_length=64, unique=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='my_app.customer')),
            ],
        ),
    ]
